

import openai
import json

# Load your OpenAI API key (replace with your actual API key)
openai.api_key = "<API_KEY>" 

# Open and load the template JSON file
with open("story_chat.json", "r") as file:
    template = json.load(file)["prompt"]

# List of different story prompts with varied characters, settings, and conflicts
stories = [
    {
        "character": "Alice, a curious scientist",
        "setting": "a hidden underground lab",
        "conflict": "she discovers a failed experiment coming to life"
    },
    {
        "character": "Bob, a brave adventurer",
        "setting": "a mysterious jungle",
        "conflict": "he is trapped and must find a way out before the storm hits"
    },
    {
        "character": "Lily, a skilled detective",
        "setting": "an abandoned mansion",
        "conflict": "she uncovers a dark secret about the mansion's owner"
    }
]

# Generate and print the stories
for story in stories:
    # Fill in the placeholders in the template
    story_prompt = template.format(**story)
    
    # Make a request to the OpenAI API to generate the story
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",  # Use the appropriate chat model
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": story_prompt}
        ],
        max_tokens=300,  # Control the length of the story
        temperature=0.7  # Creativity level (higher value = more creative)
    )
    
    # Print the story generated by ChatGPT
    print(response['choices'][0]['message']['content'].strip())
